export default () => ({
  title: [
    `Изучить теорию`,
    `Сделать домашку`,
    `Пройти интенсив на соточку`,
  ][Math.floor(Math.random() * 3)],
  dueDate: [
    Date.now() + 1 + Math.floor(Math.random() * 7) * 24 * 60 * 60 * 1000,
    Date.now() - 1 - Math.floor(Math.random() * 7) * 24 * 60 * 60 * 1000,
  ][Math.floor(Math.random() * 2)],
  tags: new Set([
    `homework`,
    `theory`,
    `practice`,
    `intensive`,
    `keks`,
    `brainstorm`,
    `htmlacademy`,
    `lazydays`,
    `hardwork`,
  ]),
  picture: `http://picsum.photos/100/100?r=${Math.random()}`,
  color: [
    `black`,
    `yellow`,
    `blue`,
    `green`,
    `pink`,
  ][Math.floor(Math.random() * 5)],
  repeatingDays: {
    Mo: [true, false][Math.floor(Math.random() * 2)],
    Tu: [true, false][Math.floor(Math.random() * 2)],
    We: [true, false][Math.floor(Math.random() * 2)],
    Th: [true, false][Math.floor(Math.random() * 2)],
    Fr: [true, false][Math.floor(Math.random() * 2)],
    Sa: [true, false][Math.floor(Math.random() * 2)],
    Su: [true, false][Math.floor(Math.random() * 2)],
  },
  isFavorite: [true, false][Math.floor(Math.random() * 2)],
  isDone: [true, false][Math.floor(Math.random() * 2)],
});
